### ISSUE TITLE
allow merging of datasets

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#118]
specification forthcoming

**Comment by prabhasp** [comment]
A spec, for feedback:

```
http://bamboo.io/merged_dataset?datasets='["_dataset1_id","_dataset2_id", "_dataset3_id"]'
    &columns='["geopoint", "mylga", "respondent_name", "photo", ....]'
> returns a new {"id" : _merged_dataset _id}
```

which contains the columns as specified in the columns field + a `source` column*, and as pulled from rows of _dataset1_id, .... Num rows in merged dataset = n1 + n2 + n3. (Or a `source_id` and `source_name` column). It might also make sense to let columns to be specified as 

```
{merged_column_name: "geopoint", source_column_names: 
    {"_dataset1_id": "column1", "_dataset2_id": "column2" "_dataset3_id": "column3"}}
```

but even the former specs would get us quite far.

Additional Requirement: links from `_dataset_1`, `_dataset2`, `_dataset3`, etc. to `_merged_dataset`, so that if any data is added on to the former datasets, the latter gets updated.

This would enable a lot, including data collection monitoring dashboards for Nigeria, as well as for Ethiopia Soil Tracking product.

**Comment by pld** [comment]
This should be a POST request since it is altering data, with JSON for the params, maybe like

```
POST /merge

{
    "dataset_id1": {
        "source_column1": "destination_column1",
        "source_column2": "destination_column2",
        ...
    },
    "dataset_id2": {
        "source_columnA": "destination_column1",
        "source_columnB": "destination_column2",
         ...
    },
    ...
}
```

where all destination columns must be the same for each dataset.

If there is no column to column mapping (i.e. the datasets you're merging are all of the same structure) specifying for each is unnecessary, is it a burden?

Would it be helpful/necessary to allow missing columns?  Maybe `dataset_id2` doesn't have the `district` column but it still have the `gps` so you want to merge but just leave that column empty,

```
district | gps
2           3
1           2
            4
            2
```

where the first 2 rows are from `dataset_id1` and the last 2 rows are from `dataset_id2`, wouwe couldallow the merge but leave the fields empty.

**Comment by prabhasp** [comment]
The proposal looks good, we can avoid the convenience function until
requested. Re: empties: is there a good way to support this across types?
(ie, do we have an n/a for ints,booleans, etc). If so, we should support it.

prabhas pokharel
skype/twitter/fb: prabhasp
+1 347 9487654

**Comment by modilabs-starscream** [comment]
For now requests will look like,

```
POST
/datasets/merge

BODY
datasets=["dataset_id1", "dataset_id2"]
```

This will add the rows in the datasets with IDs dataset_id1 and dataset_id2 into the same new dataset.  If there are columns in dataset_id1 not in dataset_id2 the fields for those columns will be null for rows in dataset_id2, and vice-versa.

In the future a `map` parameter will be supported for column mappings, using the syntax descibed in the previous comment.

**Comment by mejymejy** [comment]
one note of clarification: the order in which the dataset_ids appear in the `datasets` list is the order in which the rows will be appended (e.g. the rows from `dataset_id1` will precede those from `dataset_id2`, etc.)

**Comment by prabhasp** [comment]
@mejymejy what about for streaming datasets? (in the order you specified, and the order they come in after that?)

**Comment by pld** [comment]
yes

**Comment by mejymejy** [comment]
just an update...

we have decided that there is no inherent "order" in datasets.  if an order is desired, then there should be a column that indicates this in the data (e.g. index column, timestamp, etc.) that can be used to perform the sort.  in other words, datasets are considered to be sets (strictly-speaking) of key-value pairs that can be converted to matrices (where order matters) via some sorting scheme.

**Comment by prabhasp** [comment]
like

On Fri, Sep 28, 2012 at 12:58 PM, Mark Johnston notifications@github.comwrote:

> just an update...
> 
> we have decided that there is no inherent "order" in datasets. if an order
> is desired, then there should be a column that indicates this in the data
> (e.g. index column, timestamp, etc.) that can be used to perform the sort.
> in other words, datasets are considered to be sets (strictly-speaking) of
> key-value pairs that can be converted to matrices (where order matters) via
> some sorting scheme.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/118#issuecomment-8983715.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp
