### ISSUE TITLE
Row merge with column mapping

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#152]
```
POST
/datasets/merge

BODY
datasets=["dataset_id1", "dataset_id2"]
map={
    "dataset_id1": {
        "source_column1": "destination_column1",
        "source_column2": "destination_column2",
        ...
    },
    "dataset_id2": {
        "source_columnA": "destination_column1",
        "source_columnB": "destination_column2",
         ...
    },
    ...
}
```

**Comment by mejymejy** [comment]
It may be useful to allow a constant column to be mapped here for an entire dataset in order to distinguish them in the merged dataset.  For example, I may be merging the data from three rounds of collection where I would want to add a column called `round_number` and have values of `1`, `2`, and `3` for all rows in datasets 1, 2, and 3, respectively.  Discussion of syntax for this can come at a later point.
