### ISSUE TITLE
should we build the schema for datasets before the async call?

### ISSUE THREAD

**Issue by mejymejy** [SEL-Columbia/bamboo#284]
this would allow one to immediately query the info, whereas now you have to wait until the import_dataset async task completes in order to find out this information.  it seems that most of the time spent in the import is actually saving the records, though the schema building takes time (maybe more than it should?) it may still be reasonable to do this before returning the new dataset id to the user.  the benefit is that you can get info about your dataset right away, but i suppose that the downside is that the info will tell you things about the dataset that "aren't quite true."  for example it may say that your dataset has 1,000 rows and 50 columns though it may not have completed importing and, thus, will not return that number until the import is finished.  still, it will return the status which will classify it as "pending" and signifying that the data is not yet ready for query/use, so maybe that is a non-issue...

i think it may be worth trying this approach.  in my mind, the main reason that we shouldn't is if it takes an inordinate amount of time on large datasets.  @pld, any thoughts?

**Comment by pld** [comment]
Same conclusion for me.  The numbers being incorrect is a non-issue because it's marked as pending.  The reason to not do this is if it takes a long time.

I think right now we would need to load the dataset into a DataFrame to get the schema out, and this might take a while for large datasets.  But, we could just grab the first row of the dataset and load that, although I wonder if this will give an incorrect schema (e.g. N/A values in the first row).

**Comment by pld** [comment]
@mejymejy I'm taking it out of the milestone, let's add it back once we have an action plan.  If you think we need to figure it out before finishing the milestone re-add.

**Comment by mejymejy** [comment]
@pld sounds good... i can try it with the nigeria data or some other large dataset and then we can decide from there what the best plan might be

**Comment by pld** [comment]
given the performance research this far seems like the answer is no, closing.
