### ISSUE TITLE
Refer to columns in calculations with a special format: {column}

### ISSUE THREAD

**Issue by pld** [SEL-Columbia/bamboo#309]
This supersedes the following issues:
- https://github.com/modilabs/bamboo/issues/213
- https://github.com/modilabs/bamboo/issues/252

We've discussed this before and I think it is (completely?) unanimous that users should refer to their columns with the column names (and not use the slugs) in calculations.

We then need to support column names with whitespace and some special characters.  We can do this by having a format for referring to a column.  We never decided what this format should be.

Requirements:
- format must prefix and suffix the column name
- we must disallow using the prefix and suffix anywhere else in calculations
  - implies none of [these](http://bamboo.io/docs/core.html#formula-parser) charactes can be in the prefix or suffix

Suggestions:
- lets encode all references to columns as `{column name}`
- we never allow `{` or `}` in a column name and never use it in our expressions

If we think we may want to use `{` or `}` we can do it [django-style](https://www.youtube.com/watch?v=9bZkp7q19f0): `{{column name}}`.

@mejymejy and @prabhasp what do you guys think?

P.S.  I belive, if we make this change, it will not affect existing formulas, only new ones.

**Comment by prabhasp** [comment]
{{column name}} sounds good to me, given django precedent.
R does `column name`, which I don't like as much.

I think I may have opined before that slugs potentially _never_ be user-exposed, that users should deal only with column names. After having talked to many more people, I now renege on that position. Software such as R, Stata, and others have strict character formatting rules, and because of the need for users to have data interact with those systems, we should, somehow, expose slugging. But it doesn't have to be the only way to do these things (ie, this issue).
I guess corollary is that I know think the priority of this issue isn't super duper high.

**Comment by pld** [comment]
OK, that makes sense.  In that case, how about we close this issue and add one to ensure that column names which are equivalent to reserved words (sum, etc.) get slugged (become sum_, etc.)?
