### ISSUE TITLE
Add support for `distinct` queries

### ISSUE THREAD

**Issue by rgaudin** [SEL-Columbia/bamboo#341]
I'd like to have the ability to filter data similarly to a DISTINCT SQL command.

Typical use case is to count individual _items_ from a field so it would be good to be able to somehow chain that with count queries.

Maybe something like `select={"barcode": "$distinct"}` in a query or summary ?

See [MongoDB's distinct](http://docs.mongodb.org/manual/reference/method/db.collection.distinct/).

**Comment by pld** [comment]
Queries go straight through to Mongo, https://github.com/modilabs/bamboo/blob/master/bamboo/models/abstract_model.py#L86

Does Mongo not behave properly when you submit that query?  (maybe we strip it along the way)

**Comment by rgaudin** [comment]
From what I see in the linked mongo doc, it's a different _command_: `distinct()`. I believe, we forward bamboo queries to the `find()` command as an argument.

**Comment by pld** [comment]
Ah I see, a bit inconvenient.  PyMongo docs indicate the same, http://api.mongodb.org/python/1.4/api/pymongo/collection.html#pymongo.collection.Collection.distinct

**Comment by pld** [comment]
I've worked on this and the way you can interact with a distinct is limited, it can only be a single key.  Given that, I'm planning to add it as an optional parameter to show.  I like the in select syntax, but then what to do is undefined if the user passes,

``` json
{"barcode": "$distinct", "name":"$distinct"}
```

Or... we could have one distinct in mongo and the rest in python.  We cannot chain distinct calls because distinct returns a list (or array in MongoDB), so the first distinct would be to mongo and the rest would have to be implemented in python on a list.  The previous will also cause performance issues for (any number of) distinct queries on large datasets.

**Comment by pld** [comment]
WIP https://github.com/modilabs/bamboo/compare/distinct
