### ISSUE TITLE
behavior on recreating calculationss

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#351]
People will likely recreate calculations as a result of 
- running a script that contains a calcution 
- they want to correct a calculation when they've made a mistake

I'm confused on what the current behavior is now

Is the calculation overwritten?  Are they just repeated (another column added?)

Is it possible to have the same calculation name with different formulas?  

From an end users standpoint, the least confusing thing is to require the calculation names to be unique.

**Comment by mberg** [comment]
You can replicate if it's for a different aggregation group but the formula should probably stay the same no?

**Comment by pld** [comment]
When added to a dataset each calculation was a label and a slug.  The label can be any ASCII character string, with spaces, special characters, etc. and it can also be duplicated in the dataset.  The slug is alphanumerics and underscore ("_") and is made to be unique by appending underscore if otherwise it would be a duplicate.

For example, if you add two calculations both with the name "student_teacher_ratio" internally they will both have the label "student_teacher_ratio" but their slugs will be "student_teach_ratio" and "student_teach_ratio_", for the second one you have added.

In any case, when you refer to calculated columns in formulas you must use their slugs. 

To overwrite a calculation you must delete the calculation and then add it again.  I think this is enough functionality.  If it's a common use case, we can add an `update_calculation` method to pybamboo and other libraries which does this is a single step.

 To answer your questions:
1. No, calculations are not overwritten.
2. The calculation label will be repeated but it will have a unique slug, that you can determine via the schema with an `info` call
3. It is possible to have the same calculation label with different formulas, but impossible to have the same calculation slug with different formulas.
4. For different aggregation groups you can change the formula if you want, it's completely at the user's discretion.  It would certainly make sense to keep the formulas the same but that is not a requirement, although pybamboo and other libraries could enforce this if they liked.

(I agree that this should all be in the docs.)

**Comment by mberg** [comment]
Ok thanks this is very helpful.  I'm glad that the slugs are different.
 I'm still confused on the difference between a slug and a label though.

**Comment by pld** [comment]
A label is meant to be human readable and a slug must be able to be a column name in a DataFrame.

Use case is, suppose the you want to build a bar chart from your bamboo data, and you want the x/y-axis labels to be human readable so you store a formula with name "Student Teacher Ratio", you can get then get the column by slug using "Student_Teacher_Ratio" from bamboo and convert the slug to a y-axis label using the dataset schema, which you pull from `info`.
