### ISSUE TITLE
Schema (at least for integers) not being set properly from formhub

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#371]
For this form the math and verbal (integers) are being imported as strings

http://formhub.org/mberg/forms/grades/form.xls

http://bamboo.io/datasets/ae2d4544c200419fac9ec0e6c5693ccc/info

**Comment by mberg** [comment]
As a result, I'm getting errors like this I think because it's a string (right?)

curl -X POST -d "name=grade_total&formula=math+verbal" http://bamboo.io/calculations/ae2d4544c200419fac9ec0e6c5693ccc
{"error": "Parse Failure for string \"math verbal\": Expected end of text (at char 5), (line:1, col:6)"}mberg@ubuntu:~/Documents/drishti$

**Comment by pld** [comment]
Can you provide the original dataset that was uploaded?

**Comment by mberg** [comment]
It was done via the enketo Web form.

Publish to formhub, fill an enekto form then link to bamboo via formhub

**Comment by pld** [comment]
If you look at the dataset you'll see that those columns are string since one of their entries is a string, see the first row here, http://bamboo.io/datasets/ae2d4544c200419fac9ec0e6c5693ccc.

A number in quotes is a string in [json](http://www.json.org/)

To force them to be interpreted as numbers you can add a schema file.  We have an issue for letting users set the OLAP type, https://github.com/modilabs/bamboo/issues/267, perhaps we'd want to let them set the simpletype, or upload a schema after the fact.

These are more serious changes, @mejymejy what do you think?

**Comment by mberg** [comment]
Is this an enketo issue?

**Comment by mberg** [comment]
Ok confirmed. I created the initial data from ODK and not collect and both
verbal and math are now integers.

http://bamboo.io/datasets/f2c548326e5c4c5b903264538ef10d89/info

Martijn is this something we can look at?

**Comment by mberg** [comment]
Ok really weird.  You submit via enketo and it switches back to "string"

verbal:
{
- olap_type: "dimension",
- cardinality: 3,
- simpletype: "string",
- label: "verbal"

},

I tried submitting via ODK and it doesn't change back

**Comment by mberg** [comment]
Schema when first submission is from ODK.

Issue is that the schema is _changing_ with new submissions

schema: {
start: {
olap_type: "measure",
cardinality: 2,
simpletype: "datetime",
label: "start"
},
end: {
olap_type: "measure",
cardinality: 1,
simpletype: "datetime",
label: "end"
},
verbal: {
olap_type: "measure",
cardinality: 2,
simpletype: "integer",
label: "verbal"
},
grade: {
olap_type: "measure",
cardinality: 2,
simpletype: "integer",
label: "grade"
},
student_id: {
olap_type: "measure",
cardinality: 2,
simpletype: "integer",
label: "student_id"
},
math: {
olap_type: "measure",
cardinality: 2,
simpletype: "integer",
label: "math"
}
}
}

**Comment by prabhasp** [comment]
So the issue is that a string submission is being made to an integer field.
Question is: what should be done?

I think bamboo so far takes a very data-centric view, where the data
defines the schema. However, it might make sense to fix it so that
type-conflicting updates are rejected. Perhaps this can be a dataset
option, or it can happen once a schema is actually updated by the user?

(On a side note: enketo/formhub should be changed that empty string
submissions aren't made to integer fields. This will cause problems for
js-based processors, for example, on the formhub map, if we add an integer
visualizer. @MartijnR)

On Sat, Jan 5, 2013 at 12:12 AM, Matt Berg notifications@github.com wrote:

> Schema when first submission is from ODK.
> 
> Issue is that the schema is _changing_ with new submissions
> 
> schema: {
> start: {
> olap_type: "measure",
> cardinality: 2,
> simpletype: "datetime",
> label: "start"
> },
> end: {
> olap_type: "measure",
> cardinality: 1,
> simpletype: "datetime",
> label: "end"
> },
> verbal: {
> olap_type: "measure",
> cardinality: 2,
> simpletype: "integer",
> label: "verbal"
> },
> grade: {
> olap_type: "measure",
> cardinality: 2,
> simpletype: "integer",
> label: "grade"
> },
> student_id: {
> olap_type: "measure",
> cardinality: 2,
> simpletype: "integer",
> label: "student_id"
> },
> math: {
> olap_type: "measure",
> cardinality: 2,
> simpletype: "integer",
> label: "math"
> }
> }
> }
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modilabs/bamboo/issues/371#issuecomment-11911056.

## 

Prabhas Pokharel
http://twitter.com/prabhasp
US mobile: +1 347 948 7654
skype/facebook/whatever: prabhasp

**Comment by pld** [comment]
Made a new issue for this, https://github.com/modilabs/bamboo/issues/375, let me know what you think the best option is.
