### ISSUE TITLE
better error messages on calculation creation

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#381]
Right now bamboo often tells you a calculation has successfully been created just to have it stay in the pending state which usually means it fails.

I realize this is a result of the asynchornous of this.  So when you check the calculations page instead of pending it would be helpful if it displayed a more descriptive error message.  Right now it's quite frustrating as you have no idea why things aren't working.

**Comment by pld** [comment]
We can catch exceptions in the calculation task and set the calculation to failed if one is raised.  Still, I would think that most of the times a calculation fails (or for now stays in the pending state forever) it is because of an error in bamboo that we should address.

So, whenever this happens please create an issue with a link to the dataset and the calculation that got stuck in pending, the more information the better.  If it turns out to be user error, we should catch whatever exception is being raised and set the state to failed.  If it turns out to be an error in bamboo we should fix it so that the next time it goes to the ready state.
