### ISSUE TITLE
ability to create dataset from json

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#389]
This seems like it would be really handy.  Not sure how tricky this would be.

Maybe we support only json files that are flat initially (or we automatically flatten).

I would love to be able to load these easily into bamboo for example 

https://github.com/mberg/github-africa/tree/master/users

**Comment by pld** [comment]
This is actually pretty straightforward, the problem is that there is no canonical JSON format for representing CSVs (or even if there is, there are multiple ways one could express a CSV as JSON).

We can be circular about it and proscribe the correct JSON upload format is the JSON format we export our data in.

**Comment by pld** [comment]
We'll support support JSON uploads where the file contains a list of dicts, each dict being a row.
