### ISSUE TITLE
set_olap_type doesnt reflect in summary, should it

### ISSUE THREAD

**Issue by larryweya** [SEL-Columbia/bamboo#508]
With a field that has values 1 and 2 for yes and no respectively, bamboo's dataset summary shows this with a numeric breakdown i.e. mean, average etc. When I use set_olap_type on the field and change it to dimension, it doesn't reflect on the summary, shouldn't it?

**Comment by pld** [comment]
From the client perspective, I'd agree that it should, so that the summary reflects the current state of the system and the user knows what will happen when they conduct queries.

From the system perspective, we need to keep track of the OLAP types that you can set a column, we should ensure that changing the summary OLAP type will not affect this.

I think the conclusion is the summary should reflect the currently set OLAP type.
